package main

import (
	"bufio"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/sambeau/basil/server/auth"
	"github.com/sambeau/basil/server/config"
	"github.com/sambeau/basil/server/deploy"
)

// releaseBranch is the branch a push must move to publish a release
// (DESIGN-git-deploy §7, default `live`). FEAT-154 makes it configurable.
const releaseBranch = config.DefaultReleaseBranch

const indexParsContent = `<h1>"🌿 Hello from Basil 👋"</h1>
`

// gitignoreContent is short now: runtime state is no longer inside the
// repository at all, it lives in the site's data root.
const gitignoreContent = `# Editor and OS noise
.DS_Store
*.swp

# Nothing else belongs here: Basil keeps databases, logs, certificates,
# caches and uploads in the site's data directory, outside this repository.
`

// preCommitHook formats .pars files before they are committed. Formatting is
// never allowed to block a release, so this warns and continues when the
// formatter is not installed.
const preCommitHook = `#!/bin/sh
# Basil pre-commit hook: format staged .pars files.
# Installed by 'basil --init'. Enable in a fresh clone with:
#     git config core.hooksPath .githooks

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.pars$' || true)
[ -z "$files" ] && exit 0

if ! command -v basil >/dev/null 2>&1; then
	echo "basil: 'basil' not found, skipping .pars formatting" >&2
	exit 0
fi

echo "$files" | while read -r f; do
	[ -f "$f" ] || continue
	basil fmt -w "$f" && git add "$f"
done
exit 0
`

// basilYAMLTemplate is the generated configuration. Everything persistent
// resolves against the site's data directory, which is outside the release,
// so none of it needs to be named here.
const basilYAMLTemplate = `# Basil Configuration
# Generated by: basil --init

server:
  host: %q
  port: %d
%s
# Site mode - filesystem-based routing
# Files in site/ are served at their path (e.g., site/index.pars → /)
site:
  path: ./site

# Public directory for static files (CSS, JS, images)
public_dir: ./public

# Authentication. Required to push to this site: an API key in the auth
# database is what authorises a deploy.
auth:
  enabled: true

# The Git endpoint at /.git/ is on because this site has a repository
# (site.git). Pushing always requires an API key from the auth database
# above. To turn the endpoint off entirely:
# git:
#   enabled: false

# Where site code may write. <data_dir>/uploads is always writable and is
# served at /__uploads/; add more entries here if site code needs them.
# Relative paths resolve against the data directory, so a deploy never
# destroys what is written there.
# security:
#   allow_write:
#     - ./scratch

# Persistent state lives outside the release, so a deploy never destroys it.
# Uncomment to move it somewhere other than <site root>/data:
# data_dir: ./data

# SQLite database (uncomment to enable). Relative paths resolve against the
# data directory, never against the release.
# database:
#   path: ./data.db

logging:
  level: info
  format: text
`

// localGitignoreContent guards the future push path. In the legacy layout
// DataDir IS the project directory, so every database, cache, certificate and
// upload lands next to the code - deliberately unlike the server-mode file,
// where state lives outside the repository entirely.
const localGitignoreContent = `# Basil runtime state. In a local folder Basil writes its databases,
# caches, certificates and uploads next to your code; none of it belongs
# in the repository you will one day push to a server.
.basil-auth.db*
dev_logs.db*
*.db
*.db-wal
*.db-shm
certs/
cache/
search/
uploads/

# Editor and OS noise
.DS_Store
*.swp
`

// localBasilYAMLTemplate is the generated configuration for a local site.
// It carries no auth:, git: or https: block: none of them mean anything
// until the site has a server, and a server forces the ones it needs on when
// it serves a site root, so their absence here can never disable anything
// remote.
const localBasilYAMLTemplate = `# Basil Configuration
# Generated by: basil --init

server:
  host: %q
  port: %d

# Site mode - filesystem-based routing
# Files in site/ are served at their path (e.g., site/index.pars → /)
site:
  path: ./site

# Public directory for static files (CSS, JS, images)
public_dir: ./public

# This file describes the site, not the machine it runs on. Per-person
# settings live under developers.<name>, where they cannot collide, and are
# applied with: basil --dev -as sam
# developers:
#   sam:
#     port: 3001

# Where Basil keeps databases, caches and uploads. In this folder that is
# the folder itself; uncomment to move it somewhere else.
# data_dir: ./data

# SQLite database (uncomment to enable). Relative paths resolve against the
# data directory.
# database:
#   path: ./data.db

logging:
  level: info
  format: text
`

// initOptions carries everything runInit needs, so the whole command is
// testable without a terminal, without sudo and without $USER.
type initOptions struct {
	Folder      string
	Host        string
	Admin       string
	Server      bool // build the server deploy topology instead of a local folder
	NoGit       bool // local mode only: do not create a repository
	Stdin       io.Reader
	Stdout      io.Writer
	Stderr      io.Writer
	Interactive bool                // a terminal is attached: we may prompt
	Geteuid     func() int          // injectable for tests
	Getenv      func(string) string // injectable for tests
}

// runInitCommand creates a new Basil site. The default is the plain local
// folder Basil has always been about; --server builds the deploy topology,
// which belongs on the machine that receives deploys.
func runInitCommand(opts initOptions) error {
	if opts.Geteuid == nil {
		opts.Geteuid = os.Geteuid
	}
	if opts.Getenv == nil {
		opts.Getenv = os.Getenv
	}
	if opts.Server {
		return runServerInit(opts)
	}
	return runLocalInit(opts)
}

// runLocalInit creates the simple folder: basil.yaml, site/, public/. No
// repository to receive deploys, no auth database, no API key - none of it
// means anything until the site has a server, and the graduation path adds
// them on the server, not here.
func runLocalInit(opts initOptions) (err error) {
	stdout := opts.Stdout

	if strings.TrimSpace(opts.Admin) != "" {
		return fmt.Errorf("--admin names the first account on a deployment server and is only meaningful with --server\n" +
			"  a local site has no accounts: basil --init mysite\n" +
			"  to set up the server instead: basil --init mysite --server --host mysite.example.com --admin sam")
	}

	host := opts.Host
	if host == "" {
		host = "localhost"
	}
	if err := validateHost(host); err != nil {
		return err
	}

	root, err := filepath.Abs(opts.Folder)
	if err != nil {
		return fmt.Errorf("invalid path '%s': %w", opts.Folder, err)
	}
	if err := checkEmptyTarget(root, opts.Folder); err != nil {
		return err
	}
	if opts.Geteuid() == 0 {
		if err := checkTargetIsSafeForRoot(root, opts.Folder); err != nil {
			return err
		}
	}
	_, statErr := os.Stat(root)
	createdRoot := os.IsNotExist(statErr)

	// Half a site is worse than none: the next attempt fails with "folder is
	// not empty", which points at the wrong problem.
	defer func() {
		if err != nil {
			cleanupLocalInitTree(root, createdRoot)
		}
	}()

	// Git is a nicety here, not a gate: a missing binary degrades to a plain
	// folder, because the plain folder is the product in this mode.
	useGit := !opts.NoGit
	if useGit {
		if _, err := exec.LookPath("git"); err != nil {
			useGit = false
		}
	}

	if err := writeLocalStarterSite(root, host, useGit); err != nil {
		return err
	}

	// The config is proved before success is reported, as server mode does.
	if _, err := verifyGeneratedConfig(root); err != nil {
		return err
	}

	if useGit {
		if err := initLocalRepository(root); err != nil {
			return err
		}
	}

	printLocalInitSummary(stdout, root, useGit)
	return nil
}

// writeLocalStarterSite writes the local folder's files. The pre-commit hook
// is written only when a repository will be created: an inert .githooks/ in a
// folder with no repository is a puzzle, not a nicety.
func writeLocalStarterSite(root, host string, useGit bool) error {
	files := map[string]struct {
		content string
		mode    os.FileMode
	}{
		config.ConfigFileName: {fmt.Sprintf(localBasilYAMLTemplate, host, 8080), 0644},
		".gitignore":          {localGitignoreContent, 0644},
		"site/index.pars":     {indexParsContent, 0644},
		"public/.keep":        {"", 0644},
	}
	if useGit {
		files[".githooks/pre-commit"] = struct {
			content string
			mode    os.FileMode
		}{preCommitHook, 0755}
	}
	for name, f := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return fmt.Errorf("creating %s: %w", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(f.content), f.mode); err != nil {
			return fmt.Errorf("creating %s: %w", name, err)
		}
	}
	return nil
}

// initLocalRepository makes the folder clone-shaped from day one, so
// graduating to a server later is two commands and not a restructure. The
// branch is `main`: this is the developer's own history, not the release
// branch a server publishes from.
func initLocalRepository(root string) error {
	steps := [][]string{
		{"init", "--initial-branch=main"},
		{"config", "core.hooksPath", ".githooks"},
		{"add", "-A"},
		{"-c", "user.name=Basil", "-c", "user.email=basil@localhost",
			"commit", "--no-verify", "-m", "Initial site"},
	}
	for _, args := range steps {
		if err := runGit(root, args...); err != nil {
			return fmt.Errorf("creating the repository: %w", err)
		}
	}
	return nil
}

// cleanupLocalInitTree is cleanupInitTree for the local layout: the same
// promise, a different list of entries.
func cleanupLocalInitTree(root string, createdRoot bool) {
	if createdRoot {
		os.RemoveAll(root)
		return
	}
	for _, name := range []string{
		config.ConfigFileName,
		".gitignore",
		".githooks",
		".git",
		"site",
		"public",
	} {
		os.RemoveAll(filepath.Join(root, name))
	}
}

// printLocalInitSummary prints the layout and the one command that runs it.
// No API key, no clone command: neither exists in this mode. The last line is
// the bridge to the other half of the product, and is a signpost, not a nudge.
func printLocalInitSummary(stdout io.Writer, root string, useGit bool) {
	name := filepath.Base(root)

	fmt.Fprintf(stdout, "Created Basil site '%s'\n\n", name)
	fmt.Fprintf(stdout, "  %s/\n", root)
	fmt.Fprintf(stdout, "  ├── %-14s configuration\n", config.ConfigFileName)
	fmt.Fprintf(stdout, "  ├── %-14s your pages (index.pars is the home page)\n", "site/")
	fmt.Fprintf(stdout, "  └── %-14s static files (CSS, JS, images)\n", "public/")
	fmt.Fprintf(stdout, "\n")
	if useGit {
		fmt.Fprintf(stdout, "  ✓ git repository on 'main', with the starter site committed\n")
		fmt.Fprintf(stdout, "  ✓ pre-commit formatting hook\n")
		fmt.Fprintf(stdout, "\n")
	}

	fmt.Fprintf(stdout, "Start the server:\n")
	fmt.Fprintf(stdout, "  cd %s && basil --dev\n", name)
	fmt.Fprintf(stdout, "\n")
	fmt.Fprintf(stdout, "When you want to put it on a server: run 'basil --init <dir> --server' on the\nbox, then connect this folder - see docs/guide/deployment.md\n")
	fmt.Fprintf(stdout, "\n")
}

// runServerInit creates the deploy topology: bare repository, releases,
// `current`, the data root, the auth database and the first API key. This is
// the machine that receives deploys, and it is unchanged from FEAT-152.
func runServerInit(opts initOptions) (err error) {
	stdout, stderr := opts.Stdout, opts.Stderr

	if opts.Host == "" {
		return fmt.Errorf("--host is required: it is written to server.host, and a public server refuses to start without it\n" +
			"  e.g. basil --init mysite --host mysite.example.com --admin sam\n" +
			"  use --host localhost for a site you will only run with --dev")
	}

	if err := validateHost(opts.Host); err != nil {
		return err
	}

	admin, err := resolveAdminName(opts)
	if err != nil {
		return err
	}
	if admin == "root" {
		fmt.Fprintf(stderr, "warning: creating the admin account as 'root'. Basil accounts are separate from operating system accounts; a person's name reads better in the deploy record.\n")
	}

	if _, err := exec.LookPath("git"); err != nil {
		return fmt.Errorf("git is not installed or not on PATH: basil --init creates a repository and deploys its first release from it")
	}

	root, err := filepath.Abs(opts.Folder)
	if err != nil {
		return fmt.Errorf("invalid path '%s': %w", opts.Folder, err)
	}
	if err := checkEmptyTarget(root, opts.Folder); err != nil {
		return err
	}
	if opts.Geteuid() == 0 {
		if err := checkTargetIsSafeForRoot(root, opts.Folder); err != nil {
			return err
		}
	}
	_, statErr := os.Stat(root)
	createdRoot := os.IsNotExist(statErr)

	// Half a site is worse than none: the next attempt fails with "folder is
	// not empty", which points at the wrong problem, and the API key from
	// the failed run is already spent. Anything created here is removed
	// again unless the whole command succeeds.
	defer func() {
		if err != nil {
			cleanupInitTree(root, createdRoot)
		}
	}()

	// --- layout ---------------------------------------------------------
	repoDir := filepath.Join(root, config.BareRepoName)
	releasesDir := filepath.Join(root, config.ReleasesDirName)
	dataDir := filepath.Join(root, config.DataDirName)
	// The site root, the repository and the releases hold code, which is
	// public anyway. The data root holds the auth database, its SQLite
	// sidecars, session state and the certificate cache, so it is 0700 -
	// at least as tight as the database inside it.
	for _, dir := range []string{root, releasesDir} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("creating %s: %w", dir, err)
		}
	}
	for _, dir := range []string{dataDir, filepath.Join(dataDir, config.UploadsDirName)} {
		if err := os.MkdirAll(dir, 0700); err != nil {
			return fmt.Errorf("creating %s: %w", dir, err)
		}
	}

	// --- bare repository -------------------------------------------------
	if err := runGit(root, "init", "--bare", "--initial-branch="+releaseBranch, repoDir); err != nil {
		return fmt.Errorf("creating repository: %w", err)
	}

	// --- starter site, committed on the release branch -------------------
	work := filepath.Join(root, ".init-work")
	if err := os.MkdirAll(work, 0755); err != nil {
		return fmt.Errorf("creating working directory: %w", err)
	}
	defer os.RemoveAll(work)

	if err := writeStarterSite(work, opts.Host); err != nil {
		return err
	}

	commit, err := commitStarterSite(work, repoDir)
	if err != nil {
		return err
	}

	// --- release 1 -------------------------------------------------------
	//
	// A fresh site with no release cannot serve, so it cannot answer an ACME
	// challenge, so it has no certificate, so it cannot be cloned over
	// HTTPS, so it can never receive the push that would give it a release.
	// --init breaks that deadlock by deploying the starter site itself.
	// (DESIGN-git-deploy §5.1.1)
	releaseDir := filepath.Join(releasesDir, commit)
	if err := copyTree(work, releaseDir, ".git"); err != nil {
		return fmt.Errorf("creating first release: %w", err)
	}
	link := filepath.Join(root, config.CurrentLinkName)
	if err := os.Symlink(filepath.Join(config.ReleasesDirName, commit), link); err != nil {
		return fmt.Errorf("linking %s: %w", config.CurrentLinkName, err)
	}

	// --- the config must load before a credential is spent ---------------
	//
	// createAdmin prints an API key that is not recoverable. If the config
	// it was generated alongside cannot be loaded, the operator is left with
	// a spent key and a tree that --init refuses to re-enter, so the config
	// is proved first.
	cfg, err := verifyGeneratedConfig(releaseDir)
	if err != nil {
		return err
	}

	// --- deploy record: release 1 is a deploy like any other -------------
	//
	// Without this row the record starts empty, so the FIRST
	// `basil rollback` after the first real deploy refuses with "nothing to
	// roll back to" even though the starter release is sitting on disk.
	if err := recordInitialRelease(cfg.DeployDBPath(), repoDir, commit); err != nil {
		return err
	}

	// --- receive hooks: push-to-deploy from day one ----------------------
	//
	// Installed AFTER the starter push above, deliberately: the hooks exec
	// this basil binary, and firing them against a half-built site (no
	// release, no config yet) would refuse --init's own push. The server
	// re-installs on startup (transport unit), healing deletion and
	// binary-path drift.
	if err := deploy.InstallHooks(repoDir); err != nil {
		return fmt.Errorf("installing receive hooks: %w", err)
	}

	// --- admin account and API key ---------------------------------------
	apiKey, userID, err := createAdmin(dataDir, admin)
	if err != nil {
		return err
	}

	// --- ownership --------------------------------------------------------
	ownership := handOverOwnership(root, opts)

	// --- report -----------------------------------------------------------
	printInitSummary(stdout, opts, root, commit, admin, userID, apiKey)
	if ownership != "" {
		fmt.Fprint(stderr, ownership)
	}
	return nil
}

// resolveAdminName returns the admin account name. It is supplied or
// prompted for, never derived from the environment: --init runs on a server,
// where $USER and $SUDO_USER are usually root or a service account, so the
// environment is wrong exactly where it matters. (DESIGN-git-deploy §5.1.4)
func resolveAdminName(opts initOptions) (string, error) {
	if name := strings.TrimSpace(opts.Admin); name != "" {
		return name, nil
	}
	if !opts.Interactive || opts.Stdin == nil {
		return "", fmt.Errorf("--admin is required: it names the person who will own this site's first account\n" +
			"  e.g. basil --init mysite --host mysite.example.com --admin sam\n" +
			"  it is never guessed from $USER or $SUDO_USER: --init usually runs as root, and 'root deployed 4f2a1c9' tells a team nothing")
	}
	fmt.Fprintf(opts.Stdout, "Admin account name: ")
	line, err := bufio.NewReader(opts.Stdin).ReadString('\n')
	if err != nil && strings.TrimSpace(line) == "" {
		return "", fmt.Errorf("--admin is required (nothing was entered)")
	}
	name := strings.TrimSpace(line)
	if name == "" {
		return "", fmt.Errorf("--admin is required (nothing was entered)")
	}
	return name, nil
}

// verifyGeneratedConfig proves the generated basil.yaml parses and validates
// before --init does anything irreversible, and returns the loaded config so
// the caller can resolve site paths (the deploy record) the same way the
// server will.
func verifyGeneratedConfig(releaseDir string) (*config.Config, error) {
	path := filepath.Join(releaseDir, config.ConfigFileName)
	cfg, err := config.Load(path, os.Getenv)
	if err != nil {
		return nil, fmt.Errorf("the generated %s is not loadable: %w", config.ConfigFileName, err)
	}
	if err := config.Validate(cfg); err != nil {
		return nil, fmt.Errorf("the generated %s is not valid: %w", config.ConfigFileName, err)
	}
	return cfg, nil
}

// recordInitialRelease writes release 1 into the deploy record. --init IS
// the first deploy, and a record that omits it misleads later: rollback's
// "previous" and `basil releases` both read the record, not releases/.
// The author comes from the starter commit itself, matching the engine.
func recordInitialRelease(recordPath, repoDir, commit string) error {
	start := time.Now()
	authorName, authorEmail := "", ""
	if out, err := gitOutput(repoDir, "log", "-1", "--format=%an%x00%ae", commit); err == nil {
		authorName, authorEmail, _ = strings.Cut(strings.TrimSpace(out), "\x00")
	}
	rec, err := deploy.OpenRecord(recordPath)
	if err != nil {
		return fmt.Errorf("creating the deploy record: %w", err)
	}
	defer rec.Close()
	if err := rec.Add(deploy.Entry{
		CommitSHA:   commit,
		Trigger:     deploy.TriggerInit,
		Publisher:   "init",
		AuthorName:  authorName,
		AuthorEmail: authorEmail,
		StartedAt:   start,
		Duration:    time.Since(start),
		Outcome:     deploy.OutcomeDeployed,
	}); err != nil {
		return fmt.Errorf("recording release 1: %w", err)
	}
	return nil
}

// cleanupInitTree removes what --init created after a failure part-way
// through. It removes the whole root only when --init created it; an empty
// directory the operator made themselves is left in place, emptied of the
// entries this command added.
func cleanupInitTree(root string, createdRoot bool) {
	if createdRoot {
		os.RemoveAll(root)
		return
	}
	for _, name := range []string{
		config.BareRepoName,
		config.ReleasesDirName,
		config.DataDirName,
		config.CurrentLinkName,
		".init-work",
	} {
		os.RemoveAll(filepath.Join(root, name))
	}
}

// checkEmptyTarget refuses anything but a missing or empty directory.
func checkEmptyTarget(root, given string) error {
	info, err := os.Stat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("failed to access path '%s': %w", given, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("path '%s' exists but is a file, not a folder", given)
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return fmt.Errorf("failed to read directory '%s': %w", given, err)
	}
	if len(entries) > 0 {
		return fmt.Errorf("folder '%s' is not empty - use an empty folder or choose a different name", given)
	}
	return nil
}

// checkTargetIsSafeForRoot refuses a target another account could tamper
// with while --init is running as root.
//
// --init shells out to git four times between the emptiness check and the
// last write, and every write it makes (MkdirAll, WriteFile, Symlink)
// follows symlinks. If the target's parent is writable by an unprivileged
// account - `sudo basil --init /tmp/mysite`, or a shared /srv/sites - that
// account can swap a component for a symlink during the window and have
// root write through it. Requiring the target not to exist, and its parent
// not to be writable by others without the sticky bit, closes that window
// without changing the ordinary non-root path at all.
func checkTargetIsSafeForRoot(root, given string) error {
	if _, err := os.Lstat(root); err == nil {
		return fmt.Errorf("running as root, '%s' must not exist yet: --init creates it, and writing into a directory another account could have prepared lets that account redirect root's writes\n  remove it, or choose a name that does not exist", given)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("failed to access path '%s': %w", given, err)
	}

	parent := filepath.Dir(root)
	info, err := os.Stat(parent)
	if err != nil {
		return fmt.Errorf("failed to access the parent directory '%s': %w", parent, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("'%s' is not a directory", parent)
	}
	mode := info.Mode()
	if mode.Perm()&0o022 != 0 && mode&os.ModeSticky == 0 {
		return fmt.Errorf("running as root, refusing to create '%s': its parent %s is %04o - writable by other accounts and not sticky, so another account can swap a path component while --init runs\n  create the site somewhere only root can write, e.g. /srv", given, parent, mode.Perm())
	}
	return nil
}

// writeStarterSite writes the files that become release 1.
func writeStarterSite(dir, host string) error {
	port := 443
	extra := "\n  https:\n    auto: true\n"
	if config.IsLocalHost(host) {
		port = 8080
		extra = ""
	}
	files := map[string]struct {
		content string
		mode    os.FileMode
	}{
		config.ConfigFileName:  {fmt.Sprintf(basilYAMLTemplate, host, port, extra), 0644},
		".gitignore":           {gitignoreContent, 0644},
		"site/index.pars":      {indexParsContent, 0644},
		"public/.keep":         {"", 0644},
		".githooks/pre-commit": {preCommitHook, 0755},
	}
	for name, f := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return fmt.Errorf("creating %s: %w", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, []byte(f.content), f.mode); err != nil {
			return fmt.Errorf("creating %s: %w", name, err)
		}
	}
	return nil
}

// validateHost refuses anything that is not a hostname or an IP literal.
//
// The host is written into basil.yaml, and the API key is printed once and
// is not recoverable, so a host that makes the config unloadable costs the
// operator the credential and the whole tree: --init refuses to re-run into
// a non-empty directory. `*` alone is enough - it is a YAML alias indicator
// - and a value carrying a newline would inject top-level keys into the file
// that governs auth, TLS and security.allow_write. Checked before anything
// is created.
func validateHost(host string) error {
	const usage = "\n  a hostname (mysite.example.com), 'localhost', or an IP address"
	if len(host) > 253 {
		return fmt.Errorf("--host %q is too long (max 253 characters)%s", host, usage)
	}
	if net.ParseIP(host) != nil {
		return nil
	}
	if !hostnamePattern.MatchString(host) {
		return fmt.Errorf("--host %q is not a valid hostname%s", host, usage)
	}
	return nil
}

// hostnamePattern matches a DNS name: labels of letters, digits and hyphens,
// separated by dots, no leading or trailing hyphen.
var hostnamePattern = regexp.MustCompile(`^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)*$`)

// commitStarterSite commits the starter site on the release branch, pushes
// it into the bare repository and returns the commit id.
func commitStarterSite(work, repoDir string) (string, error) {
	steps := [][]string{
		{"init", "--initial-branch=" + releaseBranch},
		{"config", "core.hooksPath", ".githooks"},
		{"add", "-A"},
		{"-c", "user.name=Basil", "-c", "user.email=basil@localhost",
			"commit", "--no-verify", "-m", "Initial site"},
	}
	for _, args := range steps {
		if err := runGit(work, args...); err != nil {
			return "", fmt.Errorf("committing starter site: %w", err)
		}
	}

	out, err := gitOutput(work, "rev-parse", "HEAD")
	if err != nil {
		return "", fmt.Errorf("reading the initial commit: %w", err)
	}
	commit := strings.TrimSpace(out)

	if err := runGit(work, "push", "--quiet", repoDir, releaseBranch+":"+releaseBranch); err != nil {
		return "", fmt.Errorf("publishing the starter site: %w", err)
	}
	// A clone should check out the release branch.
	if err := runGit(repoDir, "symbolic-ref", "HEAD", "refs/heads/"+releaseBranch); err != nil {
		return "", fmt.Errorf("setting the repository default branch: %w", err)
	}
	return commit, nil
}

// createAdmin creates the first account and its API key. The key is returned
// so it can be printed once and never stored in plaintext.
func createAdmin(dataDir, name string) (apiKey, userID string, err error) {
	db, err := auth.OpenOrCreateDB(dataDir)
	if err != nil {
		return "", "", fmt.Errorf("creating the authentication database: %w", err)
	}
	defer db.Close()

	count, err := db.UserCount()
	if err != nil {
		return "", "", fmt.Errorf("reading the authentication database: %w", err)
	}
	if count > 0 {
		// Never overwrite existing credentials.
		return "", "", fmt.Errorf("the authentication database in %s already has accounts; refusing to create another admin", dataDir)
	}

	user, err := db.CreateUserWithRole(name, "", auth.RoleAdmin)
	if err != nil {
		return "", "", fmt.Errorf("creating the admin account: %w", err)
	}
	_, key, err := db.CreateAPIKey(user.ID, "initial key")
	if err != nil {
		return "", "", fmt.Errorf("creating the API key: %w", err)
	}
	return key, user.ID, nil
}

// handOverOwnership gives the created tree to the account that will run the
// server. Without this, `sudo basil --init` followed by running Basil as an
// ordinary user fails every write, and the error points at the database
// rather than at ownership. Returns a message for stderr, or "".
func handOverOwnership(root string, opts initOptions) string {
	if opts.Geteuid() != 0 {
		return ""
	}
	sudoUser := opts.Getenv("SUDO_USER")
	if sudoUser == "" {
		return fmt.Sprintf("\nwarning: this tree is owned by root. If Basil will run as another account, hand it over:\n    sudo chown -R <user>:<group> %s\n", root)
	}
	u, err := user.Lookup(sudoUser)
	if err != nil {
		return fmt.Sprintf("\nwarning: could not look up %q (%v). Hand the tree over before starting Basil:\n    sudo chown -R %s %s\n", sudoUser, err, sudoUser, root)
	}
	uid, err1 := strconv.Atoi(u.Uid)
	gid, err2 := strconv.Atoi(u.Gid)
	if err1 != nil || err2 != nil {
		return fmt.Sprintf("\nwarning: could not read the numeric ids for %q. Hand the tree over before starting Basil:\n    sudo chown -R %s %s\n", sudoUser, sudoUser, root)
	}
	if err := chownTree(root, uid, gid); err != nil {
		return fmt.Sprintf("\nwarning: could not change ownership to %s (%v). Do it before starting Basil:\n    sudo chown -R %s %s\n", sudoUser, err, sudoUser, root)
	}
	return fmt.Sprintf("\nOwnership of %s handed to %s (uid %d).\n", root, sudoUser, uid)
}

func chownTree(root string, uid, gid int) error {
	return filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		return os.Lchown(path, uid, gid)
	})
}

// printInitSummary prints the layout, the API key (once) and the exact
// commands the developer needs next.
func printInitSummary(stdout io.Writer, opts initOptions, root, commit, admin, userID, apiKey string) {
	name := filepath.Base(root)

	fmt.Fprintf(stdout, "Created Basil site '%s'\n\n", name)
	fmt.Fprintf(stdout, "  %s/\n", root)
	fmt.Fprintf(stdout, "  ├── %-14s bare repository, served at /.git\n", config.BareRepoName+"/")
	fmt.Fprintf(stdout, "  ├── %-14s one directory per deployed commit\n", config.ReleasesDirName+"/")
	fmt.Fprintf(stdout, "  │   └── %s/  release 1 (the starter site)\n", commit)
	fmt.Fprintf(stdout, "  ├── %-14s → %s/%s\n", config.CurrentLinkName, config.ReleasesDirName, commit)
	fmt.Fprintf(stdout, "  └── %-14s databases, certificates, logs, uploads\n", config.DataDirName+"/")
	fmt.Fprintf(stdout, "      └── %s/     durable, served at %s\n", config.UploadsDirName, config.UploadsURLPrefix)
	fmt.Fprintf(stdout, "\n")
	fmt.Fprintf(stdout, "  ✓ starter site committed to '%s' and deployed as release 1\n", releaseBranch)
	fmt.Fprintf(stdout, "  ✓ admin account '%s' (%s)\n", admin, userID)
	fmt.Fprintf(stdout, "  ✓ pre-commit formatting hook\n")
	fmt.Fprintf(stdout, "  ✓ receive hooks: a push to '%s' is validated, then deployed\n", releaseBranch)
	fmt.Fprintf(stdout, "\n")
	fmt.Fprintf(stdout, "  API key: %s\n", apiKey)
	fmt.Fprintf(stdout, "  This is shown once and is not recoverable. Save it now.\n")
	fmt.Fprintf(stdout, "\n")

	fmt.Fprintf(stdout, "Start the server:\n")
	if config.IsLocalHost(opts.Host) {
		fmt.Fprintf(stdout, "  basil --dev --site %s\n", root)
	} else {
		fmt.Fprintf(stdout, "  basil --site %s\n", root)
	}
	fmt.Fprintf(stdout, "\n")
	fmt.Fprintf(stdout, "Clone it (the API key is the password; the username selects a stored\ncredential and is ignored by Basil):\n")
	fmt.Fprintf(stdout, "  git clone https://%s@%s/.git %s\n", admin, opts.Host, name)
	fmt.Fprintf(stdout, "  cd %s && git config core.hooksPath .githooks\n", name)
	fmt.Fprintf(stdout, "\n")
}

// --- small helpers -------------------------------------------------------

func runGit(dir string, args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "GIT_TERMINAL_PROMPT=0")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git %s: %v: %s", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

func gitOutput(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "GIT_TERMINAL_PROMPT=0")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return string(out), nil
}

// copyTree copies src to dst, skipping the named top-level entries.
func copyTree(src, dst string, skip ...string) error {
	skipped := make(map[string]bool, len(skip))
	for _, s := range skip {
		skipped[s] = true
	}
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return os.MkdirAll(dst, 0755)
		}
		if skipped[strings.Split(rel, string(filepath.Separator))[0]] {
			if info.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, info.Mode().Perm())
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, info.Mode().Perm())
	})
}
